### PR TITLE
Forward CLI options to cypress open and run commands

### PR DESCRIPTION
**Pull request by dmcd**
Hi @searls ,

Thanks for building this gem. Our project it at the stage where we are want to run our tests in parallel so we'd like to pass additional options to cypress:run like `--record --key=abc123 --parallel`.

Cheers

### CODE REVIEW

**Comment by searls** [comment]
Seems reasonable. I'd love a test for this that actually ensured it was working, as I'm not sure the line you added to the test script would actually fail if this stopped working (instead it just doubles the run time, no?)

**Comment by dmcd** [comment]
Yes you're right. I'm managed to get completely mixed up in that test. 
I've had another go and added an example into the README.

**Comment by searls** [comment]
Merged in from command line but github failed to detect it

**Comment by searls** [comment]
Released in 0.0.4

**Pull request closed without merging**
